spring.application.name=document-task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

server.port=8080