spring.application.name=document-task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
jwt.secret=my-super-secret-key-that-is-at-least-256-bits-in-length-id-order-to-be-secure-enough
jwt.expiration=86400000

server.port=8080