spring.application.name=document-task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanagement
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
jwt.secret=my-super-secret-key-that-is-at-least-256-bits-in-length-id-order-to-be-secure-enough
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
minio.bucket=${MINIO_BUCKET:documents}
management.endpoints.web.exposure.include=health,info,metrics,mapping
management.endpoint.health.show-details=always

server.port=8080